title: Ministry of Style
author: John Doe
email: your-email@domain.com
description: > 
  Example for Github Pages / Jekyll publishing.

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
